// Auto-generated from matchbu.xlsx (Busan sheet) via geocoding pipeline. Do not hand-edit values that should come from the source spreadsheet.
const RESTAURANTS = [
    {
        "id":  "b3",
        "seq":  1,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "어머니간장게장",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "カンジャンケジャン定食",
        "source":  "どすこい",
        "notes":  "どすこい推薦店",
        "address_road":  "부산 중구 대청로137번길 8-2 문화빌딩 1층 어머니간장게장",
        "address_lot":  "부산 중구 중앙동3가 13-3",
        "naver_url":  "https://naver.me/FhUz2Mtv",
        "google_url":  "https://maps.app.goo.gl/bPVVKXUXGT7DYN9SA",
        "lat":  35.10353,
        "lon":  129.03521,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b4",
        "seq":  2,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "청기와개미집",
        "genre":  [
                      "焼肉・肉料理",
                      "海鮮・刺身"
                  ],
        "menu":  "韓牛焼肉 ナクチ・鮑も",
        "source":  null,
        "notes":  "昔からのお勧め店 肉\u0026サンナクチ",
        "address_road":  "부산 중구 백산길 16",
        "address_lot":  "부산 중구 동광동3가 24-1",
        "naver_url":  "https://naver.me/G4WbpXEv",
        "google_url":  null,
        "lat":  35.1023532,
        "lon":  129.0339902,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b5",
        "seq":  3,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "산청돼지국밥",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  null,
        "notes":  null,
        "address_road":  "부산 중구 대청로134번길 18",
        "address_lot":  "부산 중구 동광동3가 15-2",
        "naver_url":  "https://naver.me/Gj6XOitk",
        "google_url":  null,
        "lat":  35.1013876,
        "lon":  129.0349123,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b6",
        "seq":  4,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "물레방아 즉석구이",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "焼肉",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画 チュウォンと 안금무(アンコミ:サガリ) テンジャンチゲ絶品！",
        "address_road":  "부산 중구 중앙대로41번길 11-1",
        "address_lot":  "부산 중구 중앙동1가 24-14",
        "naver_url":  "https://naver.me/xJiB2giK",
        "google_url":  null,
        "lat":  35.1011534,
        "lon":  129.0351141,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b7",
        "seq":  5,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "섬진강재첩국",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "シジミ汁定食(재첩국정식）",
        "source":  "隣の国のグルメイト",
        "notes":  "ミチョッタ",
        "address_road":  "부산 중구 광복로85번길 15-1",
        "address_lot":  "부산 중구 동광동2가 10-4",
        "naver_url":  "https://naver.me/Gxk1B59j",
        "google_url":  null,
        "lat":  35.0997175,
        "lon":  129.0348649,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b8",
        "seq":  6,
        "type":  "food",
        "visited":  true,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "제주가본점",
        "genre":  [
                      "クッパ・スープ",
                      "海鮮・刺身"
                  ],
        "menu":  "鮑がゆ",
        "source":  null,
        "notes":  "昔から日本人にも有名 ",
        "address_road":  "부산 중구 광복로85번길 8",
        "address_lot":  "부산 중구 광복동1가 5-22",
        "naver_url":  "https://naver.me/5CW4UDPL",
        "google_url":  null,
        "lat":  35.0989831,
        "lon":  129.0338757,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b9",
        "seq":  7,
        "type":  "food",
        "visited":  true,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "할매가야밀면",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "ミルミョン",
        "source":  null,
        "notes":  "釜山人は皆知ってるミルミョン 맛집 少し漢方的",
        "address_road":  "부산 중구 광복로 56-14",
        "address_lot":  "부산 중구 남포동2가 17-1",
        "naver_url":  "https://naver.me/FTXwcWeX",
        "google_url":  null,
        "lat":  35.0984,
        "lon":  129.03236,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b10",
        "seq":  8,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "개미집 광복동본점",
        "genre":  [
                      "鍋・チゲ",
                      "海鮮・刺身"
                  ],
        "menu":  "ナッコプセ",
        "source":  null,
        "notes":  "有名なナッコプセ店の本店",
        "address_road":  "부산 중구 광복로55번길 14 2층 개미집 광복직영점",
        "address_lot":  "부산 중구 창선동1가 9-3",
        "naver_url":  "https://naver.me/FEUscZuH",
        "google_url":  null,
        "lat":  35.09954,
        "lon":  129.03045,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b11",
        "seq":  9,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "1984이바구밀면 남포점",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "ミルミョン",
        "source":  "草薙チャンネル",
        "notes":  "草薙チャンネル ",
        "address_road":  "부산 중구 남포길 5-1 1층",
        "address_lot":  "부산 중구 남포동3가 6-2",
        "naver_url":  "https://naver.me/xKERgsMJ",
        "google_url":  null,
        "lat":  35.0990355,
        "lon":  129.0294188,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b12",
        "seq":  10,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "돌고래순두부",
        "genre":  [
                      "鍋・チゲ"
                  ],
        "menu":  "純豆腐",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画？ YT絶賛",
        "address_road":  "부산 중구 중구로40번길 15",
        "address_lot":  "부산 중구 신창동2가 12-5",
        "naver_url":  "https://naver.me/5GpYyjNN",
        "google_url":  null,
        "lat":  35.1014306,
        "lon":  129.0297006,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b13",
        "seq":  11,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "신창토스트",
        "genre":  [
                      "軽食・屋台グルメ"
                  ],
        "menu":  "トースト",
        "source":  null,
        "notes":  "昔から有名",
        "address_road":  "부산 중구 광복로39번길 21-1",
        "address_lot":  "부산 중구 신창동2가 29-3",
        "naver_url":  "https://naver.me/5l7vp9lW",
        "google_url":  null,
        "lat":  35.1011337,
        "lon":  129.0292902,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b14",
        "seq":  12,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "여송제",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "チョッパル",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画  めずらしい冷製チョッパル：厚切\u0026野菜やクラゲと",
        "address_road":  "부산 중구 광복로18번길 5",
        "address_lot":  "부산 중구 부평동1가 37-10",
        "naver_url":  "https://naver.me/5fIpOZxZ",
        "google_url":  null,
        "lat":  35.0989619,
        "lon":  129.0271431,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b15",
        "seq":  13,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "부평양곱창",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "コプチャン（内臓）",
        "source":  "どすこい",
        "notes":  "どすこい推薦店",
        "address_road":  "부산 중구 부평2길 17",
        "address_lot":  "부산 중구 부평동2가 24-2",
        "naver_url":  "https://naver.me/GfCsAZyr",
        "google_url":  null,
        "lat":  35.1012798,
        "lon":  129.0264866,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b16",
        "seq":  14,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "고소한맛은 코심 깡통시장본점",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "黒豆コングクス/エゴマカルグクス/小豆粥",
        "source":  "",
        "notes":  "黒豆ムルもあるので本格的？ 緑豆やかぼちゃ粥も。",
        "address_road":  "부산 중구 중구로33번길 33-1 1층",
        "address_lot":  "부산 중구 부평동2가 20-14",
        "naver_url":  "https://naver.me/G4WCt2GK",
        "google_url":  null,
        "lat":  35.1007,
        "lon":  129.0258,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b17",
        "seq":  15,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "이가네떡볶이",
        "genre":  [
                      "軽食・屋台グルメ"
                  ],
        "menu":  "トッポッキ",
        "source":  "各メディア",
        "notes":  "メディアによく出てる",
        "address_road":  "부산 중구 부평1길 48",
        "address_lot":  "부산 중구 부평동2가 16",
        "naver_url":  "https://naver.me/xdpF8G4E",
        "google_url":  null,
        "lat":  35.1013098,
        "lon":  129.0258166,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b18",
        "seq":  16,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "장우손부산어묵 깡통시장본점",
        "genre":  [
                      "軽食・屋台グルメ"
                  ],
        "menu":  "おでん 油揚げ(유부）",
        "source":  "ヒョンム計画",
        "notes":  "S社社長訪問 クァクチューブ推薦 100%練物 ",
        "address_road":  "부산 중구 중구로43번길 19-1 장우손 부산어묵",
        "address_lot":  "부산 중구 부평동1가 19-2",
        "naver_url":  "https://naver.me/GI3Jdlrn",
        "google_url":  null,
        "lat":  35.10076,
        "lon":  129.02708,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b19",
        "seq":  17,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "원조최가네돼지국밥",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ  カムジャタンもあり",
        "source":  null,
        "notes":  "釜山のグルメですかいわのお勧め",
        "address_road":  "부산 중구 흑교로31번길 7",
        "address_lot":  "부산 중구 부평동3가 72-3",
        "naver_url":  "https://naver.me/xNLXEzg4",
        "google_url":  null,
        "lat":  35.102391,
        "lon":  129.023225,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b20",
        "seq":  18,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "신창국밥 본점",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  "隣の国のグルメイト",
        "notes":  "ミチョッタ絶賛クッパ　サムソン社長来店",
        "address_road":  "부산 서구 보수대로 53",
        "address_lot":  "부산 서구 토성동1가 4-1",
        "naver_url":  "https://naver.me/xk1XUtEk",
        "google_url":  null,
        "lat":  35.1028595,
        "lon":  129.0211969,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b21",
        "seq":  19,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "원조 73년 3대 엄마집숯불꼼장어",
        "genre":  [
                      "焼肉・肉料理",
                      "海鮮・刺身"
                  ],
        "menu":  "ヌタウナギ（꼼장어）",
        "source":  null,
        "notes":  null,
        "address_road":  "부산 중구 자갈치해안로 47-2",
        "address_lot":  "부산 중구 남포동5가 113-5",
        "naver_url":  "https://naver.me/FZ27FRra",
        "google_url":  null,
        "lat":  35.096642,
        "lon":  129.0294819,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b23",
        "seq":  20,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "釜山駅",
        "area_ko":  "",
        "name":  "평산옥",
        "genre":  [
                      "焼肉・肉料理",
                      "麺類"
                  ],
        "menu":  "茹で肉(수육）열무국수(3-11月)",
        "source":  "バトルトリップ",
        "notes":  "シンドン推薦　スユク1人前から超安 バトルトリップ",
        "address_road":  "부산 동구 초량중로 26",
        "address_lot":  "부산 동구 초량동 591-11",
        "naver_url":  "https://naver.me/GBFHNQRm",
        "google_url":  null,
        "lat":  35.1219722,
        "lon":  129.0408947,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b24",
        "seq":  21,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "釜山駅",
        "area_ko":  "",
        "name":  "안목 부산역점",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  "草薙チャンネル",
        "notes":  "草薙チャンネル （番組では西面店に行ってた）",
        "address_road":  "부산 동구 중앙대로214번길 3-10 1층",
        "address_lot":  "부산 동구 초량동 1200-4",
        "naver_url":  "https://naver.me/GreX0O8L",
        "google_url":  null,
        "lat":  35.12144,
        "lon":  129.04098,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b26",
        "seq":  22,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "太宗台",
        "area_ko":  "",
        "name":  "왔다식당",
        "genre":  [
                      "鍋・チゲ"
                  ],
        "menu":  "スジ（韓牛）",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画 韓牛スジ テンジャン鍋お勧め 14時まで",
        "address_road":  "부산 영도구 하나길 811",
        "address_lot":  "부산 영도구 청학동 386-197",
        "naver_url":  "https://naver.me/F74VaAV7",
        "google_url":  null,
        "lat":  35.0800352,
        "lon":  129.0442484,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b27",
        "seq":  23,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "太宗台",
        "area_ko":  "",
        "name":  "감성조개",
        "genre":  [
                      "海鮮・刺身",
                      "麺類"
                  ],
        "menu":  "貝焼き 海鮮カルグクス",
        "source":  "バトルトリップ",
        "notes":  "バトルトリップ　シンドン推薦店",
        "address_road":  "부산 영도구 태종로 824 감성조개",
        "address_lot":  "부산 영도구 동삼동 984-4",
        "naver_url":  "https://naver.me/5tJtdOya",
        "google_url":  null,
        "lat":  35.0948265,
        "lon":  129.0509745,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b28",
        "seq":  24,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "太宗台",
        "area_ko":  "",
        "name":  "어콩",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "コングクス",
        "source":  null,
        "notes":  "豆の専門店のよう。とても濃厚そう。",
        "address_road":  "부산 영도구 동삼서로 51-4",
        "address_lot":  "부산 영도구 동삼동 219-42",
        "naver_url":  "https://naver.me/GmbcQIS4",
        "google_url":  null,
        "lat":  35.0821212,
        "lon":  129.0691556,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b30",
        "seq":  25,
        "type":  "food",
        "visited":  true,
        "line":  "1",
        "area_ja":  "凡一",
        "area_ko":  "",
        "name":  "조방낙지 범일직영점",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "ナクチ料理",
        "source":  null,
        "notes":  "以前からの有名店っぽい",
        "address_road":  "부산 동구 조방로 21",
        "address_lot":  "부산 동구 범일동 830-61",
        "naver_url":  "https://naver.me/5ZJprC6F",
        "google_url":  null,
        "lat":  35.1396675,
        "lon":  129.0613665,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b31",
        "seq":  26,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "凡一",
        "area_ko":  "",
        "name":  "원조할매낙지",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "ナクチ料理",
        "source":  null,
        "notes":  "以前からの有名店　菜都子お気に入り",
        "address_road":  "부산 부산진구 골드테마길 10",
        "address_lot":  "부산 부산진구 범천동 837-43",
        "naver_url":  "https://naver.me/Fr7pNzXC",
        "google_url":  null,
        "lat":  35.1431201,
        "lon":  129.0600424,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b33",
        "seq":  27,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "안목 서면점",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  "草薙チャンネル",
        "notes":  "草薙チャンネル（韓国観光公社推薦）",
        "address_road":  "부산 부산진구 서면로 10 1층 121, 122호",
        "address_lot":  "부산 부산진구 부전동 534-2",
        "naver_url":  "https://naver.me/FV7YdZAJ",
        "google_url":  null,
        "lat":  35.1569988,
        "lon":  129.058582,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b34",
        "seq":  28,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "개미집 서면본점",
        "genre":  [
                      "鍋・チゲ",
                      "海鮮・刺身"
                  ],
        "menu":  "ナッコプセ",
        "source":  "各メディア",
        "notes":  "いろんな番組　本店（南浦）には行った",
        "address_road":  "부산 부산진구 신천대로62번길 73",
        "address_lot":  "부산 부산진구 부전동 240-5",
        "naver_url":  "https://naver.me/52R5XQFW",
        "google_url":  null,
        "lat":  35.1540233,
        "lon":  129.0582948,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b35",
        "seq":  29,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "기장손칼국수",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "カルグクス",
        "source":  "インスタ",
        "notes":  "インスタで発見 麺モチモチ 皆んな絶賛",
        "address_road":  "부산 부산진구 서면로 56",
        "address_lot":  "부산 부산진구 부전동 256-6",
        "naver_url":  "https://naver.me/xtgpECFc",
        "google_url":  null,
        "lat":  35.1569988,
        "lon":  129.058582,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b36",
        "seq":  30,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "송정3대국밥",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  null,
        "notes":  "テジクッパ通り 伝統店",
        "address_road":  "부산 부산진구 서면로68번길 33 송정3대국밥",
        "address_lot":  "부산 부산진구 부전동 255-19",
        "naver_url":  "https://naver.me/GfCsEbvp",
        "google_url":  null,
        "lat":  35.1569988,
        "lon":  129.058582,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b37",
        "seq":  31,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "포항돼지국밥",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  null,
        "notes":  "テジクッパ通り 美味しそうな店",
        "address_road":  "부산 부산진구 서면로68번길 27 포항돼지국밥",
        "address_lot":  "부산 부산진구 부전동 255-14",
        "naver_url":  "https://naver.me/5vcHoDQO",
        "google_url":  null,
        "lat":  35.1569988,
        "lon":  129.058582,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b38",
        "seq":  32,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "문화양곱창",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "コプチャン",
        "source":  "各メディア",
        "notes":  "屋内に番号がついたイモの店が沢山並んでいるところ",
        "address_road":  "부산 부산진구 가야대로784번길 56-8",
        "address_lot":  "부산 부산진구 부전동 519-18",
        "naver_url":  "https://naver.me/GyYb1HMM",
        "google_url":  null,
        "lat":  35.1551574,
        "lon":  129.0572166,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b40",
        "seq":  33,
        "type":  "spot",
        "visited":  false,
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "name":  "나영상회",
        "genre":  [
                      "市場・買い物・両替"
                  ],
        "menu":  "両替所",
        "source":  "コネスト",
        "notes":  "西面のお得な両替所として一番有名",
        "address_road":  "부산 부산진구 서면로 56",
        "address_lot":  "부산 부산진구 부전동 256-6",
        "naver_url":  "https://naver.me/GwpMe1yw",
        "google_url":  null,
        "lat":  35.1569988,
        "lon":  129.058582,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b42",
        "seq":  34,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "市庁",
        "area_ko":  "시청",
        "name":  "콩게미 부산",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "コングクス",
        "source":  "",
        "notes":  "コンムルもある専門店。 カルグクスもある。",
        "address_road":  "부산 부산진구 양연로 8-1 1층 콩게미",
        "address_lot":  "부산 부산진구 양정동 111-7",
        "naver_url":  "https://naver.me/FRLn2mBv",
        "google_url":  null,
        "lat":  35.1729981,
        "lon":  129.0701213,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b44",
        "seq":  35,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "教大",
        "area_ko":  "교대",
        "name":  "국제밀면 본점",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "ミルミョン",
        "source":  null,
        "notes":  "ヨンファ推薦 3大ミルミョン 맛집",
        "address_road":  "부산 연제구 중앙대로1235번길 23-6",
        "address_lot":  "부산 연제구 거제동 242-23",
        "naver_url":  "https://naver.me/56R6O9m8",
        "google_url":  null,
        "lat":  35.1972883,
        "lon":  129.0783596,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b46",
        "seq":  36,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "東莱",
        "area_ko":  "동래",
        "name":  "동래할매파전",
        "genre":  [
                      "軽食・屋台グルメ"
                  ],
        "menu":  "パジョン（ねぎチヂミ）",
        "source":  null,
        "notes":  "昔から行きたかった有名店",
        "address_road":  "부산 동래구 명륜로94번길 43-10",
        "address_lot":  "부산 동래구 복천동 367-2",
        "naver_url":  "https://naver.me/5ne4QrBI",
        "google_url":  null,
        "lat":  35.2034618,
        "lon":  129.0839397,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b48",
        "seq":  37,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "久瑞",
        "area_ko":  "구서",
        "name":  "가야밀면",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "ミルミョン",
        "source":  null,
        "notes":  "ヨンファ推薦店",
        "address_road":  "부산 금정구 금정로207번길 33 가야밀면",
        "address_lot":  "부산 금정구 구서동 470-13",
        "naver_url":  "https://naver.me/5du4aREz",
        "google_url":  null,
        "lat":  35.2438645,
        "lon":  129.0895783,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b50",
        "seq":  38,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "斗実",
        "area_ko":  "두실",
        "name":  "동원장수촌",
        "genre":  [
                      "鍋・チゲ"
                  ],
        "menu":  "緑豆参鶏湯・緑豆ベクス",
        "source":  null,
        "notes":  null,
        "address_road":  "부산 금정구 금강로 577",
        "address_lot":  "부산 금정구 구서동 654-14",
        "naver_url":  "https://naver.me/5D84ixyM",
        "google_url":  null,
        "lat":  35.2534821,
        "lon":  129.0884377,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b52",
        "seq":  39,
        "type":  "food",
        "visited":  true,
        "line":  "1",
        "area_ja":  "梵魚寺",
        "area_ko":  "범어사",
        "name":  "금정산장",
        "genre":  [
                      "鍋・チゲ",
                      "焼肉・肉料理"
                  ],
        "menu":  "オリペクス・オリプルコギ",
        "source":  null,
        "notes":  "梵魚寺の入口近く ",
        "address_road":  "부산 금정구 범어사로 259 1층",
        "address_lot":  "부산 금정구 청룡동 산2-5",
        "naver_url":  "https://naver.me/5VmQJWO8",
        "google_url":  null,
        "lat":  35.2802722,
        "lon":  129.0847035,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b55",
        "seq":  40,
        "type":  "food",
        "visited":  false,
        "line":  "3",
        "area_ja":  "社稷",
        "area_ko":  "사직",
        "name":  "승하집",
        "genre":  [
                      "その他"
                  ],
        "menu":  "野球選手の母の店",
        "source":  "隣の国のグルメイト",
        "notes":  "デホ選手推薦 スンハ選手の母の手料理",
        "address_road":  "부산 동래구 사직북로5번길 31",
        "address_lot":  "부산 동래구 사직동 89-3",
        "naver_url":  "https://naver.me/I55vhD7h",
        "google_url":  null,
        "lat":  35.1961518,
        "lon":  129.0594137,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b57",
        "seq":  41,
        "type":  "spot",
        "visited":  false,
        "line":  "3",
        "area_ja":  "望美",
        "area_ko":  "망미",
        "name":  "망미중앙시장",
        "genre":  [
                      "市場・買い物・両替"
                  ],
        "menu":  "市場",
        "source":  "チャガネ",
        "notes":  "1年中 白菜などキムジャンに必要なものが買える",
        "address_road":  "부산 수영구 망미번영로 86-2",
        "address_lot":  "부산 수영구 망미동 603",
        "naver_url":  "https://naver.me/xoH6kRqb",
        "google_url":  null,
        "lat":  35.1699514,
        "lon":  129.1084563,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b59",
        "seq":  42,
        "type":  "food",
        "visited":  false,
        "line":  "3",
        "area_ja":  "水営",
        "area_ko":  "수영",
        "name":  "국이네낙지볶음",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "ナクチ",
        "source":  "チャンネツアー",
        "notes":  "チャンネツアー訪問店",
        "address_road":  "부산 수영구 연수로 410",
        "address_lot":  "부산 수영구 광안동 1070-4",
        "naver_url":  "https://naver.me/GeUR1wem",
        "google_url":  null,
        "lat":  35.1690859,
        "lon":  129.1125914,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b62",
        "seq":  43,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "毛徳",
        "area_ko":  "모덕",
        "name":  "갈치회관",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "太刀魚料理",
        "source":  "隣の国のグルメイト",
        "notes":  "ミチョッタ 超超絶賛 太刀魚定食",
        "address_road":  "부산 사상구 낙동대로 1402 1층 갈치회관",
        "address_lot":  "부산 사상구 삼락동 356-1",
        "naver_url":  "https://naver.me/FA2ftijT",
        "google_url":  null,
        "lat":  35.1944864,
        "lon":  128.9848244,
        "geo_precision":  "dong_level"
    },
    {
        "id":  "b64",
        "seq":  44,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "徳浦",
        "area_ko":  "덕포",
        "name":  "안동돼지국밥",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "テジクッパ",
        "source":  "ヒョンム計画",
        "notes":  "クァクチューブ地元民として推薦",
        "address_road":  "부산 사상구 백양대로 712 남영아파트 상가 안동돼지국밥",
        "address_lot":  "부산 사상구 덕포동 789",
        "naver_url":  "https://naver.me/G9r5twq2",
        "google_url":  null,
        "lat":  35.1754906,
        "lon":  128.9854608,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b66",
        "seq":  45,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "国際金融センター・釜山銀行",
        "area_ko":  "국제금융센터.부산은행",
        "name":  "수타혜미칼국수",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "カルグクス",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画 マート裏行きつけ 薄味 冷たい麺が美味しそう",
        "address_road":  "부산 남구 문현금융로 4",
        "address_lot":  "부산 남구 문현동 770-1",
        "naver_url":  "https://naver.me/GOPEwPdv",
        "google_url":  null,
        "lat":  35.1447874,
        "lon":  129.0649287,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b68",
        "seq":  46,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "チルゲコル",
        "area_ko":  "지게골",
        "name":  "내호냉면 본점",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "ミルミョン",
        "source":  "各メディア",
        "notes":  "創業1919 日本統治時代の牛舎に朝鮮戦争の時に避難民が住み着いた場所",
        "address_road":  "부산 남구 우암번영로26번길 17",
        "address_lot":  "부산 남구 우암동 189-671",
        "naver_url":  "https://naver.me/5YFcvVUf",
        "google_url":  null,
        "lat":  35.1257662,
        "lon":  129.07514,
        "geo_precision":  "dong_level"
    },
    {
        "id":  "b70",
        "seq":  47,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "大淵",
        "area_ko":  "대연",
        "name":  "오륙도낙지볶음",
        "genre":  [
                      "鍋・チゲ",
                      "海鮮・刺身"
                  ],
        "menu":  "ナッコプセ、ホルモン鍋など",
        "source":  "孤独のグルメ",
        "notes":  "孤独のグルメ「2019年 大晦日スペシャル 緊急指令！成田～福岡～釜山 弾丸出張編！」",
        "address_road":  "부산 남구 유엔평화로13번길 6",
        "address_lot":  "부산 남구 대연동 1737-7",
        "naver_url":  "https://naver.me/IxsBM4kp",
        "google_url":  null,
        "lat":  35.1336446,
        "lon":  129.0924332,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b72",
        "seq":  48,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "南川",
        "area_ko":  "남천",
        "name":  "연합횟집",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "刺身",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画 チュウォンと 縦斬り刺身 クロダイお勧め",
        "address_road":  "부산 수영구 황령대로489번길 59 연합횟집",
        "address_lot":  "부산 수영구 남천동 193",
        "naver_url":  "https://naver.me/GhbuMehC",
        "google_url":  null,
        "lat":  35.1446789,
        "lon":  129.1100882,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b73",
        "seq":  49,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "南川",
        "area_ko":  "남천",
        "name":  "비와술잔",
        "genre":  [
                      "海鮮・刺身"
                  ],
        "menu":  "魚料理中心おまかせ",
        "source":  "ヒョンム計画",
        "notes":  "ヒョンム計画 予約制:おまかせ(日本で営業してた)",
        "address_road":  "부산 수영구 황령대로489번길 49-8 1층",
        "address_lot":  "부산 수영구 남천동 204",
        "naver_url":  "https://naver.me/x4FLQb5q",
        "google_url":  null,
        "lat":  35.1446789,
        "lon":  129.1100882,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b75",
        "seq":  50,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "金蓮山",
        "area_ko":  "금련산",
        "name":  "이낙에산다 광안리본점",
        "genre":  [
                      "鍋・チゲ",
                      "海鮮・刺身"
                  ],
        "menu":  "ナッコプセ・ヨンポタン",
        "source":  "バトルトリップ",
        "notes":  "バトルツアー 元祖낙곱새  セウ明太ミナリジョンも！",
        "address_road":  "부산 수영구 남천바다로10번길 68 1층 이낙에산다",
        "address_lot":  "부산 수영구 남천동 29-10",
        "naver_url":  "https://naver.me/F6lTBHre",
        "google_url":  null,
        "lat":  35.1476721,
        "lon":  129.1112859,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b76",
        "seq":  51,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "金蓮山",
        "area_ko":  "금련산",
        "name":  "언양불고기 부산집본가",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "プルコギ　特殊部位など",
        "source":  null,
        "notes":  "ヨンファ推薦 キムチチゲも大好き",
        "address_road":  "부산 수영구 남천바다로33번길 8 부산집본가",
        "address_lot":  "부산 수영구 광안동 204-6",
        "naver_url":  "https://naver.me/FzSZNGcY",
        "google_url":  null,
        "lat":  35.1516753,
        "lon":  129.1163562,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b78",
        "seq":  52,
        "type":  "spot",
        "visited":  false,
        "line":  "2",
        "area_ja":  "広安里",
        "area_ko":  "",
        "name":  "민락해변공원",
        "genre":  [
                      "その他"
                  ],
        "menu":  "公園",
        "source":  null,
        "notes":  "隣で刺身を買ってここで食べる",
        "address_road":  null,
        "address_lot":  "부산 수영구 민락동 113-52",
        "naver_url":  null,
        "google_url":  null,
        "lat":  35.1585693,
        "lon":  129.127121,
        "geo_precision":  "dong_level"
    },
    {
        "id":  "b79",
        "seq":  53,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "広安里",
        "area_ko":  "",
        "name":  "나막집 광안민락점",
        "genre":  [
                      "クッパ・スープ"
                  ],
        "menu":  "デジクッパ",
        "source":  "日本番組",
        "notes":  "デジクッパのミシュラン店 さまーず訪問",
        "address_road":  "부산 수영구 민락수변로17번길 36 상가동 101호",
        "address_lot":  "부산 수영구 민락동 181-88",
        "naver_url":  "https://naver.me/F42M3IOZ",
        "google_url":  null,
        "lat":  35.1544741,
        "lon":  129.1260704,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b80",
        "seq":  54,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "広安里",
        "area_ko":  "",
        "name":  "아메리칸빌리지",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "BBQプレート",
        "source":  "草薙チャンネル",
        "notes":  "草薙チャンネル Youtube見て1番行きたかった店",
        "address_road":  "부산 수영구 민락수변로 147 3층",
        "address_lot":  "부산 수영구 민락동 110-17",
        "naver_url":  "https://naver.me/xHgITYQ2",
        "google_url":  null,
        "lat":  35.1568848,
        "lon":  129.1344951,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b82",
        "seq":  55,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "海雲台",
        "area_ko":  "해운대",
        "name":  "해운대밀면",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "ミルミョン",
        "source":  null,
        "notes":  "ヨンファ推薦 3大ミルミョン 맛집",
        "address_road":  "부산 해운대구 중동2로10번길 21",
        "address_lot":  "부산 해운대구 중동 1226-2",
        "naver_url":  "https://naver.me/G1wSjA6N",
        "google_url":  null,
        "lat":  35.1634443,
        "lon":  129.1656332,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b83",
        "seq":  56,
        "type":  "food",
        "visited":  false,
        "line":  "2",
        "area_ja":  "海雲台",
        "area_ko":  "해운대",
        "name":  "새아침식당",
        "genre":  [
                      "海鮮・刺身",
                      "鍋・チゲ"
                  ],
        "menu":  "焼魚定食  魚ジョリムなど",
        "source":  "チャガネ",
        "notes":  "チャガネ チャスンウォン推薦 焼魚定食名店",
        "address_road":  "부산 해운대구 달맞이길62번길 28 새아침맛집",
        "address_lot":  "부산 해운대구 중동 957-1",
        "naver_url":  "https://naver.me/GhbgCEAZ",
        "google_url":  null,
        "lat":  35.1578569,
        "lon":  129.1723282,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b101",
        "seq":  57,
        "type":  "food",
        "visited":  false,
        "line":  "3",
        "area_ja":  "社稷",
        "area_ko":  "사직",
        "name":  "옛정참숯불갈비 사직원조점",
        "genre":  [
                      "焼肉・肉料理"
                  ],
        "menu":  "テジカルビ",
        "source":  "隣の国のグルメイト",
        "notes":  "球場横 イデホ選手がここも美味しいと言ってた",
        "address_road":  "부산 동래구 사직로 54-4 옛정 참숯불갈비",
        "address_lot":  "부산 동래구 사직동 92-21",
        "naver_url":  "https://naver.me/5YFddfMZ",
        "google_url":  null,
        "lat":  35.1958986,
        "lon":  129.0622839,
        "geo_precision":  "road_simplified"
    },
    {
        "id":  "b102",
        "seq":  58,
        "type":  "food",
        "visited":  false,
        "line":  "3",
        "area_ja":  "社稷",
        "area_ko":  "사직",
        "name":  "주문진 막국수",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "マッククス",
        "source":  "隣の国のグルメイト",
        "notes":  "球場横 イデホ選手が言及(昔は小さい店だった）",
        "address_road":  "부산 동래구 사직로58번길 8",
        "address_lot":  "부산 동래구 사직동 92-1",
        "naver_url":  "https://naver.me/FCA8dlF1",
        "google_url":  null,
        "lat":  35.1963803,
        "lon":  129.0592539,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b103",
        "seq":  59,
        "type":  "spot",
        "visited":  false,
        "line":  "BGL",
        "area_ja":  "大沙",
        "area_ko":  "대사",
        "name":  "부산떡방앗간",
        "genre":  [
                      "軽食・屋台グルメ"
                  ],
        "menu":  "カレトク他 餅",
        "source":  "隣の国のグルメイト",
        "notes":  "餅製造・販売",
        "address_road":  "부산 강서구 제도로 1205",
        "address_lot":  "부산 강서구 강동동 112-13",
        "naver_url":  "https://naver.me/52cCFRgl",
        "google_url":  null,
        "lat":  35.1888719,
        "lon":  128.9212789,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b104",
        "seq":  60,
        "type":  "food",
        "visited":  true,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "원산면옥",
        "genre":  [
                      "麺類"
                  ],
        "menu":  "平壌冷麺 ハムン冷麺",
        "source":  null,
        "notes":  "水嚢さんお気に入り",
        "address_road":  "부산 중구 광복로 56-8",
        "address_lot":  "부산 중구 창선동1가 37-1",
        "naver_url":  "https://naver.me/GCvqFIzb",
        "google_url":  null,
        "lat":  35.09954,
        "lon":  129.03045,
        "geo_precision":  "lot_address"
    },
    {
        "id":  "b105",
        "seq":  61,
        "type":  "spot",
        "visited":  true,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "釜山観光ホテル",
        "genre":  [
                      "ホテル"
                  ],
        "menu":  "ホテル",
        "source":  null,
        "notes":  "2025.5月宿泊",
        "address_road":  "부산 중구 광복로97번길 23",
        "address_lot":  "부산 중구 동광동2가 12-1",
        "naver_url":  "https://naver.me/xmxICkDT",
        "google_url":  null,
        "lat":  35.1001982,
        "lon":  129.0347974,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b106",
        "seq":  62,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "공순대",
        "genre":  [
                      "軽食・屋台グルメ"
                  ],
        "menu":  "マクチャンスンデ",
        "source":  "老舗食堂の営業秘密",
        "notes":  "北式 マクチャン(豚テッポウ)スンデ 春雨なし",
        "address_road":  "부산 중구 중구로29번길 18-5",
        "address_lot":  "부산 중구 부평동1가 29-27",
        "naver_url":  "https://naver.me/FoENnUCN",
        "google_url":  null,
        "lat":  35.1004745,
        "lon":  129.0264592,
        "geo_precision":  "road_address"
    },
    {
        "id":  "b107",
        "seq":  63,
        "type":  "food",
        "visited":  false,
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "name":  "원조바다집",
        "genre":  [
                      "鍋・チゲ",
                      "海鮮・刺身"
                  ],
        "menu":  "水中鍋",
        "source":  "老舗食堂の営業秘密",
        "notes":  "ここだけの鍋 水中鍋:海老+ナクチ+貝",
        "address_road":  "부산 중구 광복로43번길 18-5",
        "address_lot":  "부산 중구 신창동2가 17-13",
        "naver_url":  "https://naver.me/5k7f5HCd",
        "google_url":  null,
        "lat":  35.1003591,
        "lon":  129.0296819,
        "geo_precision":  "road_address"
    }
];

const STATIONS = [
    {
        "line":  "1",
        "area_ja":  "南浦",
        "area_ko":  "",
        "order":  0
    },
    {
        "line":  "1",
        "area_ja":  "釜山駅",
        "area_ko":  "",
        "order":  1
    },
    {
        "line":  "1",
        "area_ja":  "太宗台",
        "area_ko":  "",
        "order":  2
    },
    {
        "line":  "1",
        "area_ja":  "凡一",
        "area_ko":  "",
        "order":  3
    },
    {
        "line":  "1",
        "area_ja":  "西面",
        "area_ko":  "",
        "order":  4
    },
    {
        "line":  "1",
        "area_ja":  "市庁",
        "area_ko":  "시청",
        "order":  5
    },
    {
        "line":  "1",
        "area_ja":  "教大",
        "area_ko":  "교대",
        "order":  6
    },
    {
        "line":  "1",
        "area_ja":  "東莱",
        "area_ko":  "동래",
        "order":  7
    },
    {
        "line":  "1",
        "area_ja":  "久瑞",
        "area_ko":  "구서",
        "order":  8
    },
    {
        "line":  "1",
        "area_ja":  "斗実",
        "area_ko":  "두실",
        "order":  9
    },
    {
        "line":  "1",
        "area_ja":  "梵魚寺",
        "area_ko":  "범어사",
        "order":  10
    },
    {
        "line":  "3",
        "area_ja":  "社稷",
        "area_ko":  "사직",
        "order":  11
    },
    {
        "line":  "3",
        "area_ja":  "望美",
        "area_ko":  "망미",
        "order":  12
    },
    {
        "line":  "3",
        "area_ja":  "水営",
        "area_ko":  "수영",
        "order":  13
    },
    {
        "line":  "2",
        "area_ja":  "毛徳",
        "area_ko":  "모덕",
        "order":  14
    },
    {
        "line":  "2",
        "area_ja":  "徳浦",
        "area_ko":  "덕포",
        "order":  15
    },
    {
        "line":  "2",
        "area_ja":  "国際金融センター・釜山銀行",
        "area_ko":  "국제금융센터.부산은행",
        "order":  16
    },
    {
        "line":  "2",
        "area_ja":  "チルゲコル",
        "area_ko":  "지게골",
        "order":  17
    },
    {
        "line":  "2",
        "area_ja":  "大淵",
        "area_ko":  "대연",
        "order":  18
    },
    {
        "line":  "2",
        "area_ja":  "南川",
        "area_ko":  "남천",
        "order":  19
    },
    {
        "line":  "2",
        "area_ja":  "金蓮山",
        "area_ko":  "금련산",
        "order":  20
    },
    {
        "line":  "2",
        "area_ja":  "広安里",
        "area_ko":  "",
        "order":  21
    },
    {
        "line":  "2",
        "area_ja":  "海雲台",
        "area_ko":  "해운대",
        "order":  22
    },
    {
        "line":  "BGL",
        "area_ja":  "大沙",
        "area_ko":  "대사",
        "order":  23
    }
];
